### ISSUE TITLE
I can no longer run the application

### ISSUE THREAD

**Issue by ZzZombo** [VeegaP/Dota2AdvancedDescriptions#2]
It worked fantastically and smoothly all the time, but suddenly it doesn't even start anymore. I've the latest release, my OS is Windows 10 x64. Please, can you help me? I realize from my description there is no real pointers as to why it stopped to work, but I don't know where to look for relevant info, as the application is too self-contained for me to take a closer look, so I hope you can direct me there. I didn't even change my setup between the point it used to work and the point it broke. The first one was when I applied the tool the first time in a long period, then the next day an update to DotA was shipped so I had to run it again, but it broke.

**Comment by FilippoVigani** [comment]
Hi, I just tested and it worked on my side. I would advise to do the
following:
1. Delete the language file (e.g. dota_english.txt) located at "C:\Program
Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\resource"
2. Verify game cache to re-download the file (Steam Library -> right click
Dota 2 -> Properties -> Local files tab -> Verify Integrity of game cache)
3. Delete the language files located at
"C:\Users\yourusername\AppData\Local\Dota2AdvancedDescriptions" (if you
can't find the folder, run %appdata% and navigate up one folder)
4. Finally try running the application again after following the steps
above.

EDIT: Please do let me know if you managed to fix the issue you are facing.

**Comment by ZzZombo** [comment]
Seems to work again after I deleted the one in AppData.
I've attached it in case you are interested to find out why it has been causing the issue: [dota_english.txt](https://github.com/VeegaP/Dota2AdvancedDescriptions/files/642264/dota.english.txt).

**Comment by FilippoVigani** [comment]
Thanks, I'll look into it.
Closing the thread.

**Comment by ZzZombo** [comment]
Sorry, but today it happened again. Did you figure this out yet?

**Comment by ZzZombo** [comment]
Hello again. I still have this problem. Did you fix it?

**Comment by FilippoVigani** [comment]
Hey, not yet sorry, I don't have much time lately unfortunately

**Comment by FilippoVigani** [comment]
@ZzZombo I pushed a commit that should fix the problem you were facing. Please perform the steps in my first answer, then test it again. If it does happen again let me know so we can try to reproduce the steps that cause the issue.

**Comment by ZzZombo** [comment]
Yeah, thank you, seems to have fixed the issue.
